[options]
; Database
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo_v18_2026_06_11_skr03
db_maxconn = 16

; Paths
addons_path = addons,addons_ee,addons_igm

; Server
http_port = 8070
http_interface = 127.0.0.1
workers = 0

without_demo = all

; Developer mode
dev_mode = all

; Logging
log_level = info
log_handler = :INFO

; Security
admin_passwd = admin
list_db = True
